// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgaG4p3r8h-A8mRQloaXYHssZg-U30s1E',
    appId: '1:387491281859:web:dcc3b53362000203c45b76',
    messagingSenderId: '387491281859',
    projectId: 'anjastore-d5989',
    authDomain: 'anjastore-d5989.firebaseapp.com',
    storageBucket: 'anjastore-d5989.appspot.com',
    measurementId: 'G-GQXW4Y456F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ9sRoS5_9nckOvSynLcwNPYvjrGPevBU',
    appId: '1:387491281859:android:7c5cd7491c724c2bc45b76',
    messagingSenderId: '387491281859',
    projectId: 'anjastore-d5989',
    storageBucket: 'anjastore-d5989.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL1Ye_OXdH5qQX-y-ySu2c1brtlLcOcLQ',
    appId: '1:387491281859:ios:75df81c1356aef5bc45b76',
    messagingSenderId: '387491281859',
    projectId: 'anjastore-d5989',
    storageBucket: 'anjastore-d5989.appspot.com',
    iosBundleId: 'com.anjastore.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL1Ye_OXdH5qQX-y-ySu2c1brtlLcOcLQ',
    appId: '1:387491281859:ios:a2aed6f7fe6a2e81c45b76',
    messagingSenderId: '387491281859',
    projectId: 'anjastore-d5989',
    storageBucket: 'anjastore-d5989.appspot.com',
    iosBundleId: 'com.anjastore.app.RunnerTests',
  );
}
